### PR TITLE
Added terminal to homepage

### PR DESCRIPTION
**Pull request by htmelvis**
Added terminal to homepage with basic layout and simple css based functionality. Basic homepage layout styles added.
screen shot 2015-07-10 at 12 11 13 am

### CODE REVIEW

**Comment by matsilva** [comment]
Woot! That is freakin awesome. I dont have time right now to run this locally, but the code looks good. Will test around noon if someone else doesn't get to it.

**Comment by htmelvis** [comment]
I know it is not complete. We will need to componetize the form with react to give it the extended functionality, etc. I just didn't want to hold anyone else up who was working on this onboarding process

**Comment by matsilva** [comment]
Hah, it really doesn't matter to me if you use React. That one is totally up to you.

**Comment by htmelvis** [comment]
I think we should in order to hook the blinking cursor to the input and also switch out the fields. To create the multi-step form process with notifications and errors. I am talking about something along these lines

[tympanus minimal multi-step form](http://tympanus.net/Development/FullscreenForm/)

**Comment by machuga** [comment]
Diggin it!  Adding.

**Pull request merged**
